### ISSUE TITLE
script error on firefox browser when i i use facebook

### ISSUE THREAD

**Issue by Murf1954** [mgziminsky/FacebookTrackingRemoval#30] opened 2019-09-28 00:38 UTC
# Requests about ads not being hidden will be closed without response. Follow the instructions in the "Ad blocking support" template for that.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please provide the following information:**
 - Device: [e.g. Desktop, iPhone6, etc.]
 - OS: [e.g. Windows, Linux, iOS]
 - Browser [e.g. firefox, chrome]
 - Extension Version [e.g. 1.6.1]
 - Extension Options

**Additional context**

**Comment by Murf1954** [comment] 2019-09-28 00:40
I tried to reproduce the problem but the yellow bar in the menu bar comes up and goes to fast what it says it there is a script erro  with  tracking and ad removal it says  temporarily remove it stop it or wait

**Comment by mgziminsky** [comment] 2019-09-28 04:31
I appreciate that you are trying to help, especially if you created a github account just so you could report this, but you need to understand, I can't see what you see.

The template above is meant to be filled out by you. I need at least all of that information to have the best chance of reproducing. If I can't reproduce, then the only way I have any chance of determining what the problem is is if you provide an extremely detailed description of what you see. Screenshots are a necessity in cases like this. Without them, i have no idea what you are trying to describe

**Comment by Murf1954** [comment] 2019-10-17 15:49
I will try to copy it when it comes up it says though there is a script  error and there are  three options  temporarily   remove it sti op it or wait
![2018-04-29-16-15-09-72e571](https://user-images.githubusercontent.com/31610875/67024292-29682400-f0d2-11e9-8055-00de21afe274.png)n it looks like this but say   that  your extention is causing it. I  do not  know how to stop this from happening
i get  ayellow bar accroos the address bar saying that tracking and ad removing is cause inn a script error and  the 3 iptions are tem disable it  stip it or  wait

**Comment by Murf1954** [comment] 2019-10-18 02:19
i was able to capturer what  i am talking about and will post it. This is what  i get on facebook and  do not  know how to configure it. My broswer is firefox which i get my facebook through
![Capture](https://user-images.githubusercontent.com/31610875/67060790-331e7580-f12c-11e9-950f-55529a0cdccd.PNG)

**Comment by Murf1954** [comment] 2019-10-18 02:20
how do  i stop this from happening

**Comment by Murf1954** [comment] 2019-10-20 11:57
this continues to happen

**Comment by mgziminsky** [comment] 2019-10-20 14:50
See: https://github.com/mgziminsky/FacebookTrackingRemoval/issues/31#issuecomment-544258741

**Comment by Murf1954** [comment] 2019-10-20 19:47
sorry  about this my device is  windows 7  pro desktop. Browser primary is  Firefox 69.0.3.  tracking and ad removal 1.71. is and was not my intent to upset you or make you mad I think I finally  filled out  what you wanted .  i love thus extention and it works good . Have a great vacation and  thanks for  your help

**Comment by Murf1954** [comment] 2019-10-20 19:49
although my  default  browser is Firefox  I also have  IE and   chrome on my desktop.  thank you again  and  i am sorry  i have upset you. i am not sure you can do anything  But  i thought  id ask

**Comment by mgziminsky** [comment] 2020-04-25 05:24
Is this still an issue for you? I've released several performance improvements since this issue was opened. If it's not a problem anymore, please close the issue. 

If it is still happening, then try running just my extension by itself any other extensions you have installed disabled. If that fixes it, then you likely have some other extension that is conflicting with mine, in which case there is nothing I can do for you. If it is still a problem by itself, then I need you to provide me all the information requested in the template that you still haven't included.

**Closed** 2020-05-02 17:43 UTC
