### ISSUE TITLE
Break GIF in comments section

### ISSUE THREAD

**Issue by tunguyen6** [mgziminsky/FacebookTrackingRemoval#4] opened 2017-12-12 15:09 UTC
I'm unable to play GIFs in comments section unless the add-on is disabled. Please investigate this.

**Comment by mgziminsky** [comment] 2017-12-13 19:21
Thanks for reporting. I see what the issue is, I just need to decide how I want to address it.

The issue is that FB turns gifs into lazy loaded videos that are injected on click/play, and there is of course tracking attached to it. The "Remove tracking from external links" option disables click events on non-link/media elements that contain external links, which applies to most gifs. This prevents FB from seeing your click, which also prevents the actual gif from being injected.

I'm considering doing one of the following. If you have a preference, let me know. I plan to 

1. If the FB video URL is available, inline the video version of the gif.
-- Allows play/pause
-- FB still may track this
2. Insert the actual gif
-- No play/pause
-- FB shouldn't be able to track it

I also need to decide how this feature should be exposed. I'm considering either re-using the existing "Inline videos..." option to have it happen automatically, or to possibly create a special case for gifs that apply the fix on click.

**Comment by tunguyen6** [comment] 2017-12-30 12:46
Thanks for your work and sorry for the late reply. I think advanced users who prioritize privacy can always open the GIF file as an external link to view it. If there is no way to unbreak GIFs without compromising privacy I suggest you provide an option to remove tracking from GIFs in comment section but have it unchecked by default. Like some of the other features there should be a warning beside it.

**Comment by mgziminsky** [comment] 2017-12-30 17:51
I actually just wrote up the fix for this yesterday. I expect to have the release out sometime this weekend.

I was able to get a version of option 2 working that still supports "play/pause", and it wasn't necessary to add any new config options.

**Closed** 2017-12-30 21:22 UTC
