### ISSUE TITLE
Often breaks commenting on posts

### ISSUE THREAD

**Issue by LosD** [mgziminsky/FacebookTrackingRemoval#37] opened 2020-06-10 06:58 UTC
**Describe the bug**
It seems that it sometimes breaks commenting on a post, no cursor appears in the comment field after clicking it when it happens.

To make sure FTR was the issue, I've tried enabling and disabling it, and when it is disabled (either the extension completely, or through the extension options), I never see the issue.

**To Reproduce**
1. Go to your Facebook wall.
2. Go through comment fields, clicking each.
3. Note if a cursor shows up, and if it is possible to enter text.

**Actual behavior**
For some of them (maybe 25%), there is no cursor.

**Expected behavior**
I expected a cursor showing up, and to be able to comment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1282832/84240811-d75f8d00-aafe-11ea-8b5c-edf819124cec.png)
Red arrow shows where I try to click.

**Please provide the following information:**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome (latest version)
 - Extension Version:  1.8.2
 - Extension Options:
![image](https://user-images.githubusercontent.com/1282832/84236138-708aa580-aaf7-11ea-83e9-2579b6b99bcd.png)

**Additional context**
Probably related to the hiding of an element close to the comment. A workaround used to be to click the date of the post instead, making it open by itself, then commenting often worked there. I can't get it to work now, my guess is that Facebook has changed tactics and shows the same elements when opened by itself.

**Comment by mgziminsky** [comment] 2020-06-10 07:10
Thanks for reporting, I'll look into it more tomorrow, but I was unable to reproduce doing some quick checks just now. Would you also provide a screenshot of where exactly you are trying to click that isn't working in case I'm looking at the wrong thing.

**Comment by LosD** [comment] 2020-06-10 07:48
Sure, updated comment. That post it happens for me every time, by the way: https://www.facebook.com/notes/sort-s%C3%B8ndag/playliste-uge-24-2020-sort-s%C3%B8ndag-med-m%C3%A5nedens-mesterv%C3%A6rk-mastodons-crack-the-sk/10158384431393637/

(I remove personal identifiable information from the screenshot, but I guess it doesn't really matter when it's a public post, especially when I then link the post 😄)

I guess it could be some kind of interaction with another extension. Are there any extensions you've seen issues with before?

**Comment by LosD** [comment] 2020-06-10 07:51
Just played around with the developer toolbar, and it seems they're using a `<div>` with the "Write a comment..." placeholder on top of a contenteditable `<div>`:
``` html
<div class="_7c-l">
    <div class=" _65td" contenteditable="true"></div>
    <div class="_7c-t FBTR-PROCESSED">Write a comment...</div>
</div>
```

If I delete the placeholder, I can comment.

**Comment by LosD** [comment] 2020-06-10 08:02
Original, without the extension active:
``` html
<div class="_5rp7">
	<div class="_1p1t">
		<div class="_1p1v" id="placeholder-8mjef" style="white-space: pre-wrap;">Write a comment...</div>
	</div>
	<div class="_5rpb">
		<div aria-describedby="placeholder-8mjef" aria-label="Write a comment..." class="notranslate _5rpu" contenteditable="true" role="textbox" spellcheck="true" style="outline: none; user-select: text; white-space: pre-wrap; overflow-wrap: break-word;">
			<div data-contents="true">
				<div class="" data-block="true" data-editor="8mjef" data-offset-key="7g7n7-0-0">
					<div data-offset-key="7g7n7-0-0" class="_1mf _1mj">
						<span data-offset-key="7g7n7-0-0">
							<br data-text="true">
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
```

The major difference (beyond crap being removed) seems to be that the placeholder has been moved in front of the text field with the extension active. Guess some kind of event handler pass-through breaks sometimes?

**Comment by LosD** [comment] 2020-06-10 10:38
My example post stopped doing it. Others do it still. I guess it depends on what FB junk the extension needs to remove from the post at the time.

**Comment by LosD** [comment] 2020-06-11 06:34
Okaaaayyyy... I enabled the debugging, and the issue.... Simply disappeared. Disabled debugging and the issue is _still_ gone.

The underlying issue is probably still there, but if it can't be reproduced, it can't be fixed. I'll close the issue and then reopen with a log if it shows up again. Thanks for the help (and the extension!).

**Comment by LosD** [comment] 2020-06-23 13:18
Okay, it's back. And yeah, when I click on the comment box, I get:
```
Stopped propagation of mousedown from [object HTMLDivElement]
Stopped propagation of mouseup from [object HTMLDivElement]
Stopped propagation of click from [object HTMLDivElement]
```

**Comment by mikeingz** [comment] 2020-08-02 16:25
Same problem for me.
I can't comment in Group posts (but I can comment on friends' posts).
I have to disable the option "Remove tracking from external links" to make it work again.

**Comment by mgziminsky** [comment] 2020-08-03 03:37
Are you seeing the same problem as LosD, where clicking doesn't focus the input? Or are you seeing something else?
Does it happen all the time, or in a predictable way, for you? Or is it seemingly random?

I have been unable to reproduce on my end so far, but I'll look into it more again this week.

**Comment by mikeingz** [comment] 2020-08-03 04:14
The exact same problem as LosD, but only in facebook groups.
And I have the same 3 "error" messages :

Stopped propagation of mousedown from [object HTMLDivElement]
Stopped propagation of mouseup from [object HTMLDivElement]
Stopped propagation of click from [object HTMLDivElement]

The only way for me to make it work, it's to insert an emoji first, then I can focus on the input and type.
It's been like this for quite a long time actually.

**Comment by mikeingz** [comment] 2020-08-03 04:26
Here is a short video:

![facebookz](https://user-images.githubusercontent.com/2438157/89145805-71ced080-d584-11ea-81e2-34dfa9be5906.gif)

**Comment by mgziminsky** [comment] 2020-08-06 19:53
Ok, i just made some progress. It appears that this is only an issue with the old/classic FB interface. I will look into fixing it, but if you have the option to switch to the new layout then doing so should get things working again. Another workaround is to click the "Comment" button on the post, which should give you keyboard focus on the input.

<img width="390" src="https://user-images.githubusercontent.com/1260554/89575942-09028500-d81e-11ea-9d1b-c027655ecd93.png">

**Comment by mgziminsky** [comment] 2020-08-06 22:00
Ok, should be fixed now. You will get the fix when the addon updates or you can click the "Refresh Rules" button under the advanced options to force it.

**Closed by mgziminsky** 2020-08-06 22:00 UTC
Labels: bug
